spring:
  datasource:
    # url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
  #  sql:
  #    init:
  #      data-locations: classpath:data-preprod.sql
  #    tomcat:
  #      max-wait: 20000
  #      max-active: 50
  #      max-idle: 20
  #      min-idle: 15
  jackson:
    serialization:
      fail-on-empty-beans: false
  liquibase:
    change-log: classpath:/db/master.xml
    enabled: true
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-request-size: 7MB
      max-file-size: 7MB
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: false
    defer-datasource-initialization: false
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PWD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

server:
  port: 8080 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length: 1209600000 # 1000*60*60*24*14

frontend:
  url: ${PUBLIC_FRONT_URL}
mail:
  recipients: ${MAIL_RECIPIENTS}
superAdmin:
  role:
    name: SuperAdministratorGrash@p;l
fast-spring:
  username: ${FASTSPRING_USER}
  password: ${FASTSPRING_PWD}
management:
  health:
    mail:
      enabled: true
api:
  host: ${PUBLIC_API_URL}
storage:
  type: ${STORAGE_TYPE}
  minio:
    endpoint: ${MINIO_ENDPOINT}
    bucket: ${MINIO_BUCKET}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    public-endpoint: ${PUBLIC_MINIO_ENDPOINT}
  gcp:
    project-id: ${GCP_PROJECT_ID}
    bucket-name: ${GCP_BUCKET_NAME}
    value: ${GCP_JSON}